### ISSUE TITLE
Terraform Cloudflare 

### ISSUE THREAD

**Issue by hugomrdias** [web3-storage/web3.storage#1676]
Let's start terraforming cloudflare infra.

- https://developers.cloudflare.com/terraform/tutorial/track-history/
- https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs

## TODO

- [ ] Create a new repo in the web3-storage org
- [ ] Figure out where state is stored. S3 ? 
- [ ] Decide on terraform vanilla or some framework on top of it
- [ ] Start with dag.haus zone settings for DNS, SSL/TLS, Speed and Cache.
- [ ] Setup CI to deploy changes

**Comment by ericssontadashi** [comment]
Some points to add:

- regarding repo, should it be private?
- storage for tfstate I agree with s3
- for tf scripts, we could start with tfs modules and check if we need a framework later. For EP we are using terraspace.
- for startup, probably we should add users management as well

**Comment by hugomrdias** [comment]
> * regarding repo, should it be private?

start private

> * storage for tfstate I agree with s3

+1 

> * for tf scripts, we could start with tfs modules and check if we need a framework later. For EP we are using terraspace.

+1

> * for startup, probably we should add users management as well

+1

**Comment by fabiolrodriguez** [comment]
> Some points to add:
> 
> * regarding repo, should it be private?
> * storage for tfstate I agree with s3
> * for tf scripts, we could start with tfs modules and check if we need a framework later. For EP we are using terraspace.
> * for startup, probably we should add users management as well

+ 1
+ 1
+ 1
+ 1

**Comment by fabiolrodriguez** [comment]
Work saved on this repo: https://github.com/web3-storage/cf-management
