### ISSUE TITLE
Add back the "status" column to /account page pinning service table view

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#1787]
In #1760 we removed "status" from the /account page table views. We want to add it back in both places (direct uploads table and Pinning Service API table). After @olizilla's work in #1884 we can be more precise in status for direct uploads, and there was no reason to remove it from the Pinning Service API table.

# Tasks
## Direct upload view
- [x] Add back in the "Status" column
- [x] Rename column to "Complete file?"
- [ ] Modify hover-over tooltip description to say: `Indicates whether web3.storage received a complete graph of data (e.g., a full file). "Complete" indicates that web3.storage has successfully received your entire upload. If you intentionally uploaded an incomplete graph, ignore this column.`
   - If status in DB reports pinned, show "Complete"
   - Else, show whatever is in the database (with formatting like capitalization - probably can just leave that part of the code as-is)
## Pinning service API view
- [ ] Undo the part of #1760 that took out "Status" from the Pinning Service API table
## Docs
- [ ] Modify https://web3.storage/docs/how-tos/get-status/ to reflect the new state of things 
   - ✅ this is done in #1937 
   - [ ] The screenshot still needs to be updated
