### ISSUE TITLE
Update meta data for w3link, w3storage, and w3name product pages

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/web3.storage#1975]
BLOCKED until we have needed content

All 3 pages have placeholder "about" meta title and descriptions.   We need to update each page with content unique to that page so that search indexing and browser tab titles will be accurate
https://web3.storage/products/w3name/
https://web3.storage/products/web3storage/
https://web3.storage/products/w3link/

- [x] Draft content for each page and provide to engineer here in this ticket

for each page: 
- [x] update title
- [x] update description
- [x] update og:title
- [x]  update og:description
- [x] if needed, update any of the og or twitter images

**Comment by JeffLowe** [comment]
@jchris need meta copy for the 3 pages.  Once you have it, we can get @e-schneid to get it inserted in for these pages.

**Comment by JeffLowe** [comment]
BLOCKED until we have needed content

**Comment by dchoi27** [comment]
Descriptions:
- w3name: Cryptographically signed mutable pointers using IPNS. Content addressing for a dynamic web.
- w3link: HTTP gateway for lightning fast reads from the IPFS network.
- web3storage: The easiest way to store data on the decentralized web, with data available over the IPFS network and secured in Filecoin deals

**Comment by e-schneid** [comment]
I've put up a PR for the descriptions [here](https://github.com/web3-storage/web3.storage/pull/2085).  I'll keep the ticket in-progress until the above is resolved.

**Comment by JeffLowe** [comment]
If we can get the PR reviewed, we might just get the descriptions at least pushed out while we wait on answer on titles.

**Comment by dchoi27** [comment]
Good flag, let's use these:
- w3name: Products - w3name - Mutable pointers to an immutable web
- w3link: Products - w3link - Fast IPFS HTTP gateway
- web3storage: Products - web3.storage - Easy-to-use decentralized storage
