### ISSUE TITLE
Migrate DB to Postgres

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#388]
We're already getting a consistent number of operational problems from using FaunaDB for Web3.Stoarge, which doesn't bode well at the current scale. This issue tracks the things we need to do to migrate to Postgres, which we (and most others) engineers know better and will likely be more reliable.

## Plan
- [x] Define the database schema in SQL #439
- [x] Database Setup, Client and test environment #508 
- [x] Rewire API endpoints to use Postgres #441
- [x] Rewire cron jobs to use Postgres #520
- [x] Add a read-only mode to the api. Existing users can query for existing uploads, and requests go to Fauna. #452
- [x] Visualise read-only mode in the website (unfortunate, but is a useful thing to have for now and any future major maintenance). #453
- [x] Prod + Staging infra setup #541
- [x]  Sync fauna data to postgres from a known point in time in the background. #440 
- [x] Inform web3.storage users about upcoming maintenance window
- [ ]  Enable read-only mode and sync the diff between what we have in postgres and that moment.
- [ ]  Verify (need to define how) that the data in postgres is complete and accurate
- [ ] Flip the switches so reads and writes go to postgres, and disable read-only mode.
- [ ] Celebrate?!

**Comment by Gozala** [comment]
Plan of action:

- #439 
- #440
- #441

**Comment by olizilla** [comment]
To add some more nuance here, I see the migration going like this:
- #439 
- #441
- Add a `read-only` mode to the api and visualise it in the website _(unfortunate, but is a useful thing to have for now and any future major maintenance)_. Existing users can query for existing uploads, and requests go to Fauna.
- Sync fauna data to postgres from a known point in time in the background _(we need to investigate how long that takes, and what errors we could hit)_ this is captured in #440, but we need to add more detail. 
- Enable read-only mode and sync the diff between what we have in postgres and that moment.
- Verify _(need to define how)_ that the data in postgres is complete and accurate, and then flip the switches so reads and writes go to postgres, and disable read-only mode.
- Celebrate?!

**Comment by atopal** [comment]
Looks like we can close this :)
