### ISSUE TITLE
Fix technical SEO issues

### ISSUE THREAD

**Issue by atopal** [web3-storage/web3.storage#484]
Acceptance Criteria:

- [ ] Each webpage has a unique and relevant meta description
- [ ] Each page has a unique and concise title, containing keyword(s)
- [ ] robots.txt is error free and includes link to sitemap
- [ ] Permanently moved pages redirect with 301/308
- [ ] All pages have an h1 where appropriate

**Comment by atopal** [comment]
Feel free to assign this to anyone available, and please treat this as one issue. cc @zebateira
