### ISSUE TITLE
Web3.Storage team should be able to block activity from individual keys

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#536]
Sister issue to https://github.com/ipfs-shipyard/nft.storage/issues/606

Blocking would happen at Cloudflare

## Tasks
- [ ] House admin codebase in nft.storage github org

## AC:

- [ ]  admin user searches for token/key to find key
- [ ]  admin can block an individual user's key 
- [ ]  admin can unblock an individual user's key
- [ ]  blocking a key requires short text note to document reason for block
- [ ]  User with banned key can still log into UI

**Comment by JeffLowe** [comment]
@dchoi27 just want to confirm that the following are desired features of the admin:
- Banned user can still log into UI (we assume answer is yes).
- Ability to ban all keys for the user (api delivers custom error message once banned)
- Banning restricts user from creating another api key (displays custom error message)
- Flag in UI for admin user showing what service the block is for (web3 versus nft)

**Comment by atopal** [comment]
For now we are assuming that users are cooperative. If they are not, we'd have to approach this more comprehensively, because creating a new account has almost no barriers at all. For the purpose of this issue, I'd say:
* Banned users can still log in.
* Ability to ban all keys and stopping people from creating new ones can be left to next iteration
* Flag in UI to let admins know what someone is banned from sounds good.

**Comment by JeffLowe** [comment]
Closing this out to house code and tickets in nft.storage org  https://github.com/nftstorage/nft.storage/issues/606
