### ISSUE TITLE
Simple Mutability with IPNS records

### ISSUE THREAD

**Issue by alanshaw** [web3-storage/web3.storage#659]
Add a simple mutability primitive to Web3.Storage that does not tie users into Web3.Storage or centralized technologies. Build a HTTP API for Web3.Storage that allows developers to create a update mutable references using IPNS records.

More details: https://www.notion.so/protocollabs/Mutable-References-0b4df016bf9a4d538d2b7c28c8974ead

- [ ] MVP - HTTP endpoints (create + update) and client support https://github.com/web3-storage/web3.storage/pull/648
- [ ] Websockets support on server and client (listen for changes to a given key) https://github.com/web3-storage/web3.storage/pull/653
- [ ] Bundle size optimizations (pull in just the dependencies we need)
- [ ] Update [docs.web3.storage](http://docs.web3.storage) with client library additions and new tutorial(s)
- [ ] IPNS republishing (publish updated records to the DHT/pubsub so available for resolution via gateway)
- [ ] Spec site (something like [https://ipfs.github.io/pinning-services-api-spec/](https://ipfs.github.io/pinning-services-api-spec/))

Optional

- HTTP endpoints for creating keys, updating a record by sending value + private key (easy usage from the command line with `curl`)

resolves #511

**Comment by jchris** [comment]
Maybe w3name records should not expire? That seems like a potential rug pull when they expire in a year.
