### ISSUE TITLE
Create POST /pins endpoint

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#674]
### User story
As a developer, I want to be able to add a new pin object by CID on web3.storage.

We achieve this by building an API end point that will leverage the an IPFS fetching API to retrieve the file that needs to be pinned. This API is documented here: https://ipfs.github.io/pinning-services-api-spec/#tag/pins/paths/~1pins/post

### Acceptance criteria
* Pinning Services API implemented fully on web3.storage (just the HTTP part, the IPFS fetching is already taken care of.)
* Devs can use the pinning service API with their web3.storage API key

### Tasks
- [x] Validate the general architecture for API
- [x] Define & document data structures for /pins endpoint
- [x] Validation & structure for end points #649 @alexandrastoica 
- [x] Update DB Schema and DB client #651 @flea89 
- [x] Add endpoint and logic to our api service
