### ISSUE TITLE
Create GET /pins/{requestId} endpoint

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#683]
### User story
As a dev, I want to retrieve a pin object and its status.

We achieve this by building an API end point that will leverage the an IPFS fetching API to retrieve the file that needs to be pinned. This API is documented here: https://ipfs.github.io/pinning-services-api-spec/#tag/pins/paths/~1pins/post

### Acceptance criteria
* Returns a pin object and its status
* Is authorised via the user’s API key
* Pinning Services API implemented fully on web3.storage (just the HTTP part, the IPFS fetching is already taken care of.)
* Devs can use the pinning service API with their web3.storage API key

### Same preliminary tasks as #674
- [x] Validate the general architecture for API #702
- [x] Define & document data structures for /pins endpoint
- [x] Validation & structure for end points #649 @alexandrastoica 
- [x] Update DB Schema and DB client #651 @flea89 

### New task
- [ ] #702  @flea89
