### ISSUE TITLE
Create GET /pins endpoint (list)

### ISSUE THREAD

**Issue by mbommerez** [web3-storage/web3.storage#684]
### User story
As a developer, I want to be able to list all my pin objects by CID and/or name.

We achieve this by building an API end point that will leverage the an IPFS fetching API to retrieve the file that needs to be pinned. This API is documented here: https://ipfs.github.io/pinning-services-api-spec/#tag/pins/paths/~1pins/post

### Acceptance criteria
* Returns pin objects responsible for pinning the specified CID(s)
* Returns pin objects with the specified name (by default a case-sensitive, exact match)
* The response is paginated
* Can limit results
* Can filter by name - with the different types of matching defined by the spec
* Can filter by status
* Can filter by timestamp (before and after)
* Can filter by specific metadata
* Is authorised via user’s API key

### Tasks
- [x] Validate the general architecture for API
- [x] Define & document data structures for /pins endpoint
- [ ] Add endpoint and logic to our api service

**Comment by mbommerez** [comment]
This has been merged, except for two acceptance criteria:
* filter by metadata: https://app.zenhub.com/workspaces/web3storage-product-6106d25b58fccc00105aedcb/issues/web3-storage/web3.storage/798
* filter by status: https://app.zenhub.com/workspaces/web3storage-product-6106d25b58fccc00105aedcb/issues/web3-storage/web3.storage/797
