### ISSUE TITLE
Enforcing Web3 user storage capacity limits - first iteration

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/web3.storage#851]
The following describes the complete scope of the first iteration:

#### 1.  User notifications
_Notifying users who are close or over their storage limit (usually 1TB)_

- [X] Usage calculation and DB retrieval of all users > 75% usage of their quota
- [X] MailChimp ‘user quota reached’ email template with explanations on how to request more storage
  - [ ] To do: Adding tests for the MailChimp stuff & mock it
- [X] MailChimp ‘user quota exceeded’ email template with explanations on how to request more storage
  - [ ] To do: Adding tests for the MailChimp stuff & mock it
- [x] Daily automated (CRON) job to trigger to send email to all users 75-80%, 80-85%, 85-90%, 90-100%, 100%+ of their storage limit
  - [ ] To do: Uncommenting the PROD CRON job trigger - turned on for safety now

#### 2.  Admin notifications
_Notifying admins who are the recent heavy users and who is over the limit_

- [X] Usage calculation and DB retrieval of all users > 100% usage of their quota
- [x] MailChimp ‘user exceeded list’ email template
- [x] Daily automated (CRON) job to trigger to send 1 email listing all users 100%+ of their storage limit

#### 3.  Blocking upload access
_Admins blocking access to APIs for people over the limit._

- [x] Manual interface to set a restriction flag (admin.storage)
- [x] Implement filters on all APIs based on this flag

#### 4.  Request more storage
_Users requesting a higher storage limit with the reason_

- [x] Send an email to support@web3.storage
- [x] GitHub request

#### 5.  Grant more storage
_Admins granting a higher storage capacity to individual users_

- [x] Set a new user tag with storage in admin.storage

## Test plan

* Notifications
- [ ] Upload a 100MB file in Staging, adjust the user's storage limit and test the email notifications that come out.
* Blocking
- [ ] Verify if HasRestriction flag is being set in the database from admin.storage.
- [ ] See what happens with the pinning and upload APIs. User should not be able to upload anything and get an appropriate error message

**Comment by JeffLowe** [comment]
Just to clarify @dchoi27 Is this referencing limits to a user's total allowed storage on their account, rate limiting a user's api, or something else?
